### PR TITLE
all: update tests and workflows

### LINKED ISSUE #4: js_native_api.h not found on pretest build
When running npm run pretest get the following errors. Possibly a dependency is missing?
Tried adding `node-addon-api` to package.json, same result.

```
dcerisano@kronos:~/git/webgpu-napi/webidl-napi$ npm run pretest

> webidl-napi@0.0.0 pretest /home/dcerisano/git/webgpu-napi/webidl-napi
> node test/build.js

make: Entering directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu/build'
  RULE binding_gyp_webgpu_target_idl2cc_0 webgpu.cc
  CXX(target) Release/obj.target/webgpu/webgpu.o
  CXX(target) Release/obj.target/webgpu/init.o
  CXX(target) Release/obj.target/webgpu/webgpu-impl.o
../webgpu.cc:1:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
webgpu.target.mk:126: recipe for target 'Release/obj.target/webgpu/webgpu.o' failed
make: *** [Release/obj.target/webgpu/webgpu.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../webgpu-impl.h:4:0,
                 from ../webgpu-impl.cc:2:
/home/dcerisano/git/webgpu-napi/webidl-napi/webidl-napi-inl.h:7:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
webgpu.target.mk:126: recipe for target 'Release/obj.target/webgpu/webgpu-impl.o' failed
make: *** [Release/obj.target/webgpu/webgpu-impl.o] Error 1
make: Leaving directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command "/home/dcerisano/.nvm/versions/node/v10.20.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dcerisano/git/webgpu-napi/webidl-napi/test/webgpu
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
make: Entering directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example/build'
  RULE binding_gyp_example_target_idl2cc_0 example.cc
  CXX(target) Release/obj.target/example/example.o
  CXX(target) Release/obj.target/example/init.o
  CXX(target) Release/obj.target/example/example-impl.o
../example.cc:1:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
example.target.mk:126: recipe for target 'Release/obj.target/example/example.o' failed
make: *** [Release/obj.target/example/example.o] Error 1
make: *** Waiting for unfinished jobs....
../example-impl.cc:2:10: fatal error: js_native_api.h: No such file or directory
 #include "js_native_api.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
example.target.mk:126: recipe for target 'Release/obj.target/example/example-impl.o' failed
make: *** [Release/obj.target/example/example-impl.o] Error 1
make: Leaving directory '/home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command "/home/dcerisano/.nvm/versions/node/v10.20.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dcerisano/git/webgpu-napi/webidl-napi/test/webidl2_example
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

### PR DESCRIPTION
**Pull request by gabrielschulhof**
* Add switch to converter to accept custom N-API header.
* Rename the GitHub workflows to distinguish them by OS.
* Add trigger for pull request.
* Propagate individual test build failure through the builder.
* Propagate individual test failure through the runner.
* Detect Node.js version and use appropriate N-API header in tests'
  binding.gyp.

Signed-off-by: @gabrielschulhof
Fixes: https://github.com/nodejs/webidl-napi/issues/4

### CODE REVIEW

**Comment by cerisano** [comment]
Looks like the CI is using node 10. min req is node 12.

**Comment by gabrielschulhof** [comment]
@cerisano I wanna make it work on Node.js 10 as well. I'll do a conditional include of `js_native_api.h`.

**Comment by gabrielschulhof** [comment]
@kainino0x @austinEng @cerisano sorry for the long wait! I had to switch the build system from node-gyp to cmake-js to get it to properly handle the code generation for the tests on Windows, Linux, and OSX.

**Review by kainino0x — APPROVED** [review]

**Review by cerisano — COMMENTED** [review]
Very much like the switch to cmake-js from node-gyp

**Comment by gabrielschulhof** [comment]
Landed in df980a4ec6f70d687c8ccd3fef520cdaca20d47f.

**Pull request closed without merging**
