### PR TITLE
Ignore build artifacts

### PR DESCRIPTION
**Pull request by cerisano**
Just a commit to prevent generated build artifacts from getting into the repo.

### CODE REVIEW

**Review by gabrielschulhof — APPROVED** [review]

**Comment by gabrielschulhof** [comment]
@cerisano if you wish to land this PR, please
* squash to one commit, rebase to the tip of main, and add a subsystem to the subject line. In this case, I guess "repo: ignore build artifacts" would work, where "repo" is the subsystem, and the rest is the subject
* add metadata
    ```
    PR-URL: https://github.com/nodejs/webidl-napi/pull/12
    Reviewed-By: Name <email>
    ```
* It would also be good to add a line
    ```
   Signed-off-by: Name <email>
    ```

After landing, please make a comment "Landed in <commitid>." to this pull request and close as you comment.

This is a summary of the [landing procedure](https://github.com/nodejs/node/blob/master/doc/guides/collaborator-guide.md#landing-pull-requests) from the Node.js collaborator guide. The link is a bit dated, but the above is the gist of it.

**Comment by cerisano** [comment]
Landed in  8a671f8 .

**Comment by gabrielschulhof** [comment]
@cerisano please use the form
```
Signed-off-by: Firstname Lastname <emailaddress>
Reviewed-By: Firstname Lastname <emailaddress>
```
for the metadata fields involving names of people, rather than GitHub handles.

**Comment by kainino0x** [comment]
> * squash to one commit, rebase to the tip of main, and add a subsystem to the subject line. In this case, I guess "repo: ignore build artifacts" would work, where "repo" is the subsystem, and the rest is the subject

BTW, it sounds like all of this squashing/metadata work can be done in the "Squash and merge" workflow online on GitHub. (That may be what you did, I'm not sure.) You can make sure the metadata fields are set properly when editing the commit message for the squashed commit.

**Comment by cerisano** [comment]
Yes the landing procedure guide is a bit out of date, and I noticed some PRs were marked with handles rather than full names.
"Squash and merge" does indeed replace the workflow. Will use full name and email for metadata fields.

**Comment by gabrielschulhof** [comment]
I know there is automation we can use. In Node.js we have a package called node-core-utils which adds a git command `git node land` which does a bunch of traffic against GitHub APIs to properly validate and formulate a commit against main.

https://github.com/nodejs/node-core-utils/blob/master/docs/git-node.md

I don't use it, but I welcome anyone who can make something like that work with our repo.

**Pull request merged**
