### PR TITLE
all: implement object wrap

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Signed-off-by: @gabrielschulhof

### CODE REVIEW

**Review by cerisano — COMMENTED** [review]
test/class/init.cc

The test for class level idl is initializing a single class into module scope.
Is the intent to have one idl file for each class?


A single idl file for all the classes in a web API should be a goal. All the classes in the API would then be put into the same module scope by a generated master init function that calls init on each class.

Also just a note that [CTS](https://github.com/gpuweb/cts) uses a typescript definition file ([dts](https://github.com/gpuweb/types)) that contains all API classes for testing the WebGPU-API.
Pretty sure dts could be generated from webidl, making webidl the defacto master definition for a web API (would not have to maintain dts seperately).

**Comment by gabrielschulhof** [comment]
@cerisano this new test is focused on the correct code generation and object wrapping for a single interface. In the end, a WebIDL file will define as many interfaces as needed, and code for all of them will be generated and added to a single .cc file. Basically, the generator will assume that a single WebIDL file makes no references to any data types that are not defined within itself or within the WebIDL spec. So, in that sense, it will treat a WebIDL file as a compilation unit.

At

https://github.com/nodejs/webidl-napi/blob/a472ca75dc70a83eca25bd1ef16e04c3193c01be/index.js#L666

the generator incorporates into the .cc file an interface definition for each interface it encounters in a WebIDL file, after having merged mixins and partial interfaces into its definition.

**Review by cerisano — APPROVED** [review]
Approved, please see link below about a possible webidl to dts conversion script that might be useful for typescript-based testing environments like CTS.

https://github.com/microsoft/TypeScript-DOM-lib-generator

**Comment by gabrielschulhof** [comment]
Landed in 085e88513dca5c042d8dedd41ece8249a9acb828.

**Comment by kainino0x** [comment]
FYI I used that generator to generate the initial version of gpuweb/types, but I did a lot of manual work on the types after that so haven't been able to autogenerate since then.

**Comment by cerisano** [comment]
Please see issue #14 which investigates using webidl as a single source of truth to generate all dependent API signatures (impl.hh and impl.cc for N-API, impl.dts for CTS, etc).

With webidl-napi there is now a requirement for a complete webidl definition for WebGPU-API. That is a new development and could provide an excellent opportunity to have a single source of truth (master API definition).  This could make manually updating dependent API definitions uneccessary.

A good question is could the webidl also serve to generate native api headers for _new_ web APIs? The result could be the ability to create fully formed impl.cc code in many cases (eg. if the web and native sigs match exactly and are simple pass throughs - primitives, etc).

It seems like WebGPU is almost already in that state, but some manual variations are creeping in due to the absense of a single source of truth to keep everything synced automatically? Right now the native headers are the closest thing to that, but not as expressive as webidl and not suited to drive such a generator.

WebGPU is a new web API and the native headers were designed to be a close match to the official WebGPU-API spec. Older Web APIs with exsiting native headers not designed for web access might not be able to generate much if any fully formed impl.cc.

Just a note that webidl-napi is intended for _any_ web api, WebGPU being the pilot.

**Comment by kainino0x** [comment]
> A good question is could the webidl also serve to generate native api headers for new web APIs? The result could be the ability to create fully formed impl.cc code in many cases (eg. if the web and native sigs match exactly and are simple pass throughs - primitives, etc).

This doesn't make sense to me. All this does is shift the generated-handwritten boundary from one place (between the webidl-napi generated code and -impl.h/cc) to another place (between -impl.h/cc and some other thing like Dawn). You have to hand-implement some api at some point anyway, and somewhere in that implementation JavaScript-specific things like exceptions have to happen. (It doesn't make sense to expose literally every detail of the JS API in a **dependency-free** C header like webgpu.h. Let this stuff sit in a small hand-written layer in between.)

Note most of the variations between the JS and C APIs are not accidental, they're intentional design decisions due to the different natures of the languages.

P.S. please avoid editing your comments to add too much substantial content; they don't show up in email notifications, and in this case I've been seeing it change while I type this reply and I have to reread to make sure I'm not missing anything.

**Comment by cerisano** [comment]
I think some variations are there because the native headers were not generated directly from a single source of truth expressive enough to generate them (eg. webidl). 

This approach could just serve to automate the maintenance of some of the hand-written layer (impl.cc for N-API) whenever the web API spec changes. It could also update the native header and synchronize any maintenance required there. 

Again, just a thought and likely out of current scope. Now is the time to explore such things and at least try make sure avenues are kept open. The potiential for only having to update webidl and the native implementation for a given web API change is pretty compelling, with the webidl-napi compiler generating much of the hand-written layer.

Also sorry for all the updates - we could move these discussions to the webgpu-napi-cts matrix room (#13)

**Pull request closed without merging**
